CC=gcc

CFLAGS= -Wall


CFILES = server104.h \
	cs104_slave.h \
	hal_thread.h \
	hal_time.h \
	hal_base \
	iec60870_slave.h \
	liblib60870.so

serverIEC: simple_server.c
	


clean: rm -rf *.o serverIEC
